### ISSUE TITLE
Documentation organisation

### ISSUE THREAD

**Issue by svivian** [q2a/q2a.github.io#1]
Let's use this ticket for any basic initial organisational stuff for the docs.

There's a few config things we need to update (CNAME file and the URLs in `_config.yml`).

According to [this](http://jekyllrb.com/docs/configuration/#front-matter-defaults) we can set some defaults in the config too, like the layout. Pretty URLs (`permalink: pretty`) would be good too.

Any stuff we're no longer using (e.g. redirects) can be removed. Since this is for Q2A documentation, pages like "services" can stay on the main Q2A site.

Regarding organisation, I was thinking something along these lines:

- Getting started
    - Installation
    - Wordpress
    - SSO
    - Add-ons (how to install)
- Themes
    - Basic themes
    - Advanced themes
- Plugins
    - Each type of module plugin
    - Layers
    - Overrides
    - Plugin tutorial
- General development
    - External
    - Functions
- Contributing
    - Pages about contributing to Q2A code, testing and the docs.

Let me know your thoughts.

**Comment by fulldecent** [comment]
All this looks good.

Still waiting on a few things to get this project started (other Issues and under Project Status) on main page.

**Comment by svivian** [comment]
Which things are we waiting for?

- Travis CI - I've emailed Gideon about that so should be sorted soon.
- Update project details - also requested from Gideon.
- Stuff from https://github.com/q2a/question2answer/issues/374 - we can only do that once we have the documentation and structure in place.

I've been playing with a few things, mainly to get used to Jekyll/Liquid. Currently trying to organise the files as above.

**Comment by svivian** [comment]
OK basic restructuring done. Haven't updated the links within the content yet though, will sort that when I can.
