### ISSUE TITLE
Jekyll 3.0

### ISSUE THREAD

**Issue by fulldecent** [q2a/q2a.github.io#2]
GitHub just upgraded Jekyll 3.0:

https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

Confirm that no changes to our code are required for this.

**Comment by svivian** [comment]
I'm using Jekyll 3.1 locally without problems.

**Comment by fulldecent** [comment]
We are live with Jekyll 3.0 and have no problems yet, closing.
