### ISSUE TITLE
New pages

### ISSUE THREAD

**Issue by svivian** [q2a/q2a.github.io#3]
A few ideas for new documentation pages.
- [x] General Development - Code structure and application flow.
- [ ] General Development - Documentation of Q2A monolithic variables like the `$qa_content` array.
- [x] Contributing - How to contribute to Q2A code.
- [x] Contributing - How to contribute to Q2A docs.
- [x] Contributing - Adding/running unit tests.
- [ ] Contributing - Manual test rig: a list of stuff for people to test (aka Acceptance Testing). I'll write about this on the Q2A site in the near future.

**Comment by fulldecent** [comment]
FYI I have the first commit coming soon.

**Comment by fulldecent** [comment]
@svivian I updated your original comment to a task list

**Comment by fulldecent** [comment]
Bullet 4 is fixed by https://github.com/q2a/question2answer/pull/401

**Comment by fulldecent** [comment]
Checking off item 5 as we now have some (basic) unit tests. More may be added later if needed.

**Comment by svivian** [comment]
I was referring to a docs page about writing unit tests for Q2A, if that makes sense. We [have this page](http://docs.question2answer.org/contribute/unit-tests/) now so I've ticked it off.
