### ISSUE TITLE
Turn on travis-ci.org

### ISSUE THREAD

**Issue by fulldecent** [q2a/q2a.github.io#4]
For somebody with admin access here (can see SETTINGS):

Please login at https://travis-ci.org using your GitHub ID and enable testing for this repository.

**Comment by svivian** [comment]
What do we get with Travis for this repo? ie what are we testing?

**Comment by fulldecent** [comment]
Travis tests that links work, that Jekyll can build, and that HTML is valid. 

File is here https://github.com/q2a/q2a.github.io/blob/master/.travis.yml

And is referred to from the README

**Comment by svivian** [comment]
Travis is now turned on, but [the build is failing](https://travis-ci.org/q2a/q2a.github.io/builds/112707448). There is a problem building the site:

> ERROR: YOUR SITE COULD NOT BE BUILT:
>
> Invalid date '0000-00-00': Post '/vendor/bundle/ruby/2.2.0/gems/jekyll-2.4.0/lib/site_template/_posts/0000-00-00-welcome-to-jekyll.markdown.erb' does not have a valid date in the filename.

I guess because we install Jekyll from scratch it adds that file?

**Comment by fulldecent** [comment]
I got some of these errors handled. But am stuck on the latest.

@svivian I see that we have 

    markdown: redcarpet

Which is non-standard and unsupported by GitHub. Can we remove that?

**Comment by fulldecent** [comment]
Giving it a whirl, let's see what happens

**Comment by fulldecent** [comment]
Good. We are building now, have some minor legitimate problems reported in https://travis-ci.org/q2a/q2a.github.io/builds/112725528

**Comment by svivian** [comment]
> Which is non-standard and unsupported by GitHub. Can we remove that?

I changed it to redcarpet because kramdown wasn't working for inline PHP code.

I'm just working on fixing the broken links being reported from htmlproof.

**Comment by svivian** [comment]
I've reverted your change to the Markdown parser. It broke the "start_inline" option for PHP syntax highlighting (see `/plugins/tutorial.md`).

I've already brought the issue up on the kramdown repo, it should be fixed in the near future.

**Comment by svivian** [comment]
OK finally all sorted. Travis is up and running, and the build is passing!

**Comment by fulldecent** [comment]
Good news!
