### ISSUE TITLE
Update project details

### ISSUE THREAD

**Issue by fulldecent** [q2a/q2a.github.io#5]
For somebody with admin access here (can see SETTINGS):

Please update this to include a link to docs.question2answer.org

![screen shot 2016-02-04 at 4 56 48 pm](https://cloud.githubusercontent.com/assets/382183/12831089/7ffde908-cb60-11e5-84ab-b6ceee991158.png)

**Comment by svivian** [comment]
That would be @q2a / @gidgreen

The link is http://docs.question2answer.org/

**Comment by q2a** [comment]
Done - thanks!
