### ISSUE TITLE
How to handle Add-ons/Services pages?

### ISSUE THREAD

**Issue by svivian** [q2a/q2a.github.io#6]
Currently, people contact Gideon using the feedback form to let him know about plugins/themes/services they have developed, and he adds them to the respective pages.

Although they are not documentation, there may be some benefit to having these pages in the repo so that people can contribute.

Pros:

- More people can add and update the pages, for example if links are broken.
- More people can check if PRs are legit and not spammy.

Cons:

- Repo could get overloaded with PRs for adding themes/plugins and drown out documentation improvements (not too likely I think).
- Requires a Github account to make a PR or start an Issue (shouldn't be a significant "barrier to entry" though).

Thoughts?

**Comment by fulldecent** [comment]
Sounds great, can definitely be in scope.

Anybody who can make an add-on already has a GitHub account.

**Comment by svivian** [comment]
Add-ons/services are now in the docs.

**Comment by fulldecent** [comment]
Looks great!
